
import React from 'react'
import Navbar from './Navbar'
import Head from 'next/head'

const Layout = ({children}) => {
  return (
   <>
       <Head>
        <title>Hirwa Associates</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="./images/nav-logo.png" />
    
      </Head>
      
   <Navbar/>
   {children}
   </>
  )
}

export default Layout